// Package
export const REQUEST_PACKAGES = 'REQUEST_PACKAGES';
export const RECEIVE_PACKAGES = 'RECEIVE_PACKAGES';
export const SAVE_PACKAGE_BEGIN = 'SAVE_PACKAGE_BEGIN';
export const SAVE_PACKAGE_COMPLETE = 'SAVE_PACKAGE_COMPLETE';
export const PICK_PACKAGE = 'PICK_PACKAGE';
export const CLEAR_PICK_PACKAGE = 'CLEAR_PICK_PACKAGE';

// Employee
export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
export const RESET_EMPLOYEE_LIST = 'RESET_EMPLOYEE_LIST';
export const SELECTED_EMPLOYEE = 'SELECTED_EMPLOYEE';

// Vendor
export const REQUEST_VENDORS = 'REQUEST_VENDORS';
export const RECEIVE_VENDORS = 'RECEIVE_VENDORS';

// Sidebar
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

// Notification
export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
