language: node_js
node_js:
  - "8"
services:
 - docker
install:
 - yarn install --pure-lockfile
script:
 - yarn build 
 - docker build -t sameerazazi87/dakiya:`echo $TRAVIS_BUILD_NUMBER`-build .
after_success:
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker push sameerazazi87/dakiya
 