version: '2'
services:
  db:
    image: "mongo"
    volumes:
      - ./data:/data/db
  dakiya:
    image: "sameerazazi87/dakiya:0.1-beta"
    ports:
      - "9001:9001"
    volumes:
      - ./logs:/app/logs
    links:
      - db
    environment:
      - PORT
      - APP_ID
      - APP_NAME
      - MASTER_KEY
      - DATABASE_URI
      - SERVER_URL
      - PARSE_MOUNT
      - DAKIYA_WEB_MOUNT
      - DASHBOARD_MOUNT
      - DASHBOARD_USER
      - DASHBOARD_PASSWORD
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD  
      - SMTP_FROM_EMAIL
      - NODE_ENV=production








